version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: rms_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: logistics_db

  backend:
    build: .
    container_name: rms_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/logistics_db
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data:

